// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "metrima-20181117180557--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://metrima-20181117180557--hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:f431528b-b938-4695-81b4-c5212254c571",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_ZmPDLosha",
    "aws_user_pools_web_client_id": "48npsn5ismsg1kcp51sjpot526",
    "aws_mobile_analytics_app_id": "3f4f8a2af0b84329aa4e9e4dce817051",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "metrima-content-bucket",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://k5zbahevdfekzlcsng4vm74r3q.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
